### ISSUE TITLE
"Error in input value" in all FS commands

### ISSUE THREAD

**Issue by Scytmo** [thedjnK/AuTerm#11]
I'm trying to use AuTerm to connect to a Zephyr device.  The terminal window shows that I'm connected and can interact with the device shell, but when I try to use FS commands to upload/download files, I only ever get "Error in put value" shown.  I can upload/download files to this device using the mcumgr CLI from here https://github.com/apache/mynewt-mcumgr

Any suggestions?

**Comment by thedjnK** [comment]
Did you select a file and where to upload it? Working fine here:
![image](https://github.com/user-attachments/assets/0ccf02e1-ea40-406d-aa58-8095f6089685)

**Comment by Scytmo** [comment]
Yes, I did.  I get some text in the Terminal window which seems to match the console encoding of the mcumgr messages.  See attached screenshots.  How do I get that debug information I see in the top-right of your screenshot?  I have set a Log file in the Config tab, which gets created, but contains nothing.
![image](https://github.com/user-attachments/assets/e0b174c7-743a-42cf-b4fc-fd94313f229f)
![image](https://github.com/user-attachments/assets/d641c01c-bdaa-49a8-a438-4e176e9bfe19)

**Comment by thedjnK** [comment]
What version of ncs is your application built with? Can you upload the .config from it?

**Comment by Scytmo** [comment]
I believe I have found the problem.  It seems that AuTerm isn't compatible with `CONFIG_ZCBOR_CANONICAL=y`
Until recently, MCUMgr didn't even work properly with that setting, but that was fixed in https://github.com/zephyrproject-rtos/zephyr/pull/59374/ and is in the v2.6.1 ncs release (which I'm using).
You can demonstrate the problem by building the `littlefs` zephyr sample project from `zephyr/samples/subsys/fs/littlefs`, and adding the following to the `prj.conf`:

```CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_SHELL=y
CONFIG_BASE64=y
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=3072
CONFIG_MCUMGR_GRP_FS=y
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_ZCBOR_CANONICAL=y
CONFIG_CRC=y
CONFIG_SHELL=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_SHELL_STACK_SIZE=3072
```

Once it's running, you'll need to mount the filesystem in the shell with `fs mount littlefs /lfs1` (for example).
You should find that AuTerm file upload now fails with the error I reported.  If you remove the `CONFIG_ZCBOR_CANONICAL=y` line from the `prj.conf` it will work again.

Any chance of a fix for AuTerm to work with `CONFIG_ZCBOR_CANONICAL=y`?
AuTerm would be incredibly useful to me, but my project won't work without that setting.

**Comment by thedjnK** [comment]
Try version 0.29a

**Comment by uty-ianp** [comment]
> Try version 0.29a

Yes, that fixes it.  Thank you!
