### ISSUE TITLE
Auto reconnect upon device being disconnected and reconnected

### ISSUE THREAD

**Issue by thedjnK** [thedjnK/AuTerm#15]
> When the device  usb cable is unplugged from the PC the pop up window comes up.
> I replug the usb cable and then hit ‘Close’ and then click ‘Open Port’ I am back up and running – vast improvement from my version of UwTerminal.
> 
> While the dialog box is being displayed, please consider adding code so that every X ms (say 250 to 1000) it tests if the port has reappeared and if it has, then it automatically closes the dialog box and automatically reopens the port and resume as if nothing had happened (although you could add a message in the output area like “port lost/reappeared”

- [x] Windows
- [x] Linux
- [ ] mac (someone else can contribute, will not be working on this)

**Comment by thedjnK** [comment]
CC @tailoredsoft

**Comment by tailoredsoft** [comment]
Thank you.

I asked chatGPT if it is possible to register for an event that informs when a plug and play device has been plugged into a Windows/Linux/Mac PC and all three are capable of that. 
See ...
https://chatgpt.com/share/66e7e9da-3180-800e-9dc4-d1ef5d2c4bfb

**Comment by thedjnK** [comment]
Have added preliminary windows support (will need to build yourself), unfortunately whilst getting a global signal for device enumeration on windows is incredibly easy, on linux you need to do the anarchic thing of polling on a file descriptor, which needs it's own damn thread, will have to rework it to get it supported on linux. And as for mac, someone else can contribute it or it can go without!

**Comment by thedjnK** [comment]
Added in windows version 0.32, linux support will be in next release (0.33), mac will not be implemented unless someone else contributes/tests it
