### ISSUE TITLE
plugins: transport: Add NUS plugin

### ISSUE THREAD

**Issue by thedjnK** [thedjnK/AuTerm#24]
Add a NUS transport plugin to allow communication with a Zephyr device over BLE using NUS

- [x] Initial support
- [x] Builds on windows
- [x] Builds on mac
- [x] Builds on Linux
- [x] Works on windows
- [ ] ~~Works on mac~~
- [x] Works on Linux
- [x] Successfully communicates with Zephyr NUS device

**Comment by tailoredsoft** [comment]
Although already implicit I suggest that to be explicit, the first goal should be for AuTerm to provide the transport in the role of NUS gatt client using the 3 NUS uuids as default and then later the uuids can be configurable.

Stretch goal for future would be to also provide NUS as server role.

Unlike, the zephyr sample server application, this design should include FIFOs for both rx and tx characteristics and the ability to send multiple CMD write packets per interval.

When NUS is implemented with FIFOs on both sides and uplifting a connection to 2M PHY and data length extension it is possible  to achieve a throughput in excess of 500kbps

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: thedjnK ***@***.***>
Sent: Saturday, November 2, 2024 1:12:23 PM
To: thedjnK/AuTerm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thedjnK/AuTerm] plugins: transport: Add NUS plugin (Issue #24)


Add a NUS transport plugin to allow communication with a Zephyr device over BLE using NUS

  *    Initial support
  *    Builds on windows
  *    Builds on mac
  *    Builds on Linux
  *    Works on windows
  *    Works on mac
  *    Works on Linux
  *    Successfully communicates with Zephyr NUS device

**Comment by thedjnK** [comment]
> Although already implicit I suggest that to be explicit, the first goal should be for AuTerm to provide the transport in the role of NUS gatt client using the 3 NUS uuids as default and then later the uuids can be configurable.

Was thinking of having a radio selection for mode, NUS or VSP, then realised I actually have no use for VSP! Can add custom UUIDs though

> Stretch goal for future would be to also provide NUS as server role.

Would need to see, not sure how well the Qt BLE peripheral module works.

> Unlike, the zephyr sample server application, this design should include FIFOs for both rx and tx characteristics and the ability to send multiple CMD write packets per interval.

This is actually handled by the OS, in the OS BLE callbacks you basically write data and the OS stack deals with that, from the Qt perspective you just have a function for e.g. writing data or sending a notification. Like with the serial transport there will be a receive and send buffer though not sure how fast it will be. Have done firmware updates to an nRF51 many times using the current BLE code in AuTerm, no DLE in the chip but get 6KiBps or so which includes data transfer and flash erase/write (~49kbps).

The code itself will mostly be a rip of the existing AuTerm BLE MCUmgr code from https://github.com/thedjnK/AuTerm/blob/main/plugins/mcumgr/smp_bluetooth.cpp just without the MCUmgr parts and with NUS instead.

**Comment by thedjnK** [comment]
> Unlike, the zephyr sample server application, this design should include FIFOs for both rx and tx characteristics and the ability to send multiple CMD write packets per interval.

I really haven't looked into the code, using the shell sample with NUS and have this now working at a basic level, MTU seems to be 495 (zephyr sample has DLE) set and it seems a bit embarrassing on the zephyr side, `help` returns a 1885 byte response, for which it's over 249 receives which averages to 7.5 bytes per packet? So is there no buffering at all or what in the zephyr implementation?

**Comment by tailoredsoft** [comment]
Last year when I looked at the NUS sample app there was no buffering.
I then reverted to the softdevice based application using the Segger IDE.

If you want something to test against, I can provide a firmware image for the Nordic bl654 DEVKIT.

Best Regards,
Mahendra Tailor
Tailored Technology Ltd

**Comment by thedjnK** [comment]
> If you want something to test against, I can provide a firmware image for the Nordic bl654 DEVKIT.

I compiled the sample in the nRF5 SDK and it... well it manages to transfer one buffer's worth then faults, maybe because of the lack of hardware flow control or something, got a firmware that is stable with high throughput?

**Comment by tailoredsoft** [comment]
I could give you a binary image for the nrf52840 devkit where the NUS is bridged to the USB port exposed by the chip (not the segger one).
I have not fully tested that.
It is based on the nRF5 SDK sample app that has freertos in it and also some NXP UWB stuff which will try to talk to a module which is not present and so that thread will fail and loop, but the CDC and BLE thread keep going.

However, I am cleaning/reorganising my office after 4 years and it is taking lots more time than I had anticipated.
So the new image realistically cannot happen before this weekend.

Best Regards,
Mahendra Tailor
Tailored Technology Ltd

**Comment by thedjnK** [comment]
Got a build of the uart peripheral working which seems ok for doing bluetooth -> UART tests, and wow are the results interesting. Qt gives you a callback for write with response, as you would expect, they don't give you a callback for write without request, the module gets the response from the OS and just discards it... at this point I start to question if any of them have ever actually done anything with bluetooth... So you rebuild the module that that commented out, great, you start receiving callbacks to know when you can send more, and it gets a much better throughput as you'd expect, but after about 1000-2000 good packets, you get an error on the UART side data, the bluetooth side then gets a disconnect 4 seconds later, haven't looked to see if it's the peripheral locking up/crashing and rebooting or if qt/the OS bluetooth stack (in this case windows) is so abysmal that it can't handle that amount of data. Either way, it leads to a depressing outlook at you're stuck with write with response, the top throughput (with UART on 1Mbps, BLE on 1Mbps) is an absolutely pathetic ~1000bps (no that is not a typo, it is 10 times slower than 115200 baud)

**Comment by tailoredsoft** [comment]
That is why I am planning to do a linkedin blog to recommend using the BL654-US with an adapted ble_nus_client smartBASIC application.
I have not added a AT+BTR command yet to allow one to add the address of a peer so that it will automatically connect on power up and so it really works as a transparent device.

Best Regards,
Mahendra Tailor
Tailored Technology Ltd

**Comment by thedjnK** [comment]
It's a bit of a shame bluetooth on PCs seems to have not really done much in 10 years to allow for higher throughputs, but there you go...

Base implementation completed in v0.34
