### ISSUE TITLE
Request for extension to Mcumgr image upgrade to allow dfu_application.zip

### ISSUE THREAD

**Issue by andybondchiaro** [thedjnK/AuTerm#28]
Currently the AuTerm method for Mcumgr image upgrade only allows a .hex file. The nrf device manager method:
https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager
https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager

Will take a .zip file that contains a app_update.bin and a manifest.json file. Is there any possibility this could be extended?

**Comment by thedjnK** [comment]
It supports .bin files, not hex files, you can extract the zip and use `app_update.bin` directly in AuTerm (this file is also part of builds in NCS). Support for dfu_application.zip files however will not be added as they are a NCS-specific format and have no usage or support outside of NCS

**Comment by andybondchiaro** [comment]
Thank you mate!
