### ISSUE TITLE
[MCUmgr] AuTerm is Not Responding after Upload via UDP

### ISSUE THREAD

**Issue by butok** [thedjnK/AuTerm#29]
AuTerm application is Not Responding after Upload via UDP.
Steps:
1. Build & flash zephyr\samples\subsys\mgmt\mcumgr\smp_svr sample with an UDP overlay.
2. Connect EVB board via Ethernet to PC 
3. Start latest AuTerm v0.34b
4. Connect via UDP on the MCUmgr tab.
5. Go to the Upload tab and choose a binary for upload.
6. Press [Go] button.
7. Image is upload is successful  
9. BUT When the upload progress is reaching 100%, the AuTem is frizzed and Not Responding:
![image](https://github.com/user-attachments/assets/bcf00f39-266b-49eb-949f-b9586024ccd8)

NOTE:
- When uploading via UART, there is no any freeze.

**Comment by thedjnK** [comment]
Not able to replicate this with 0.34b:
![image](https://github.com/user-attachments/assets/8878f4f5-2544-4e10-83dd-9990282fb542)

**Comment by butok** [comment]
> Can you go to plugins -> open logger -> enable debug (resize for large height), then do upload again and see what it shows? Also upload the .bin here if possible, and finally check (e.g. wireshark) to see what the final packets from the device are, or if it's getting a continual stream of weird packets that don't stop

With the Logger, it froze in the following state:
![image](https://github.com/user-attachments/assets/5d18c18f-f91b-485f-b334-275b6c8d01b1)

**Comment by butok** [comment]
> and finally check (e.g. wireshark) to see what the final packets from the device are, or if it's getting a continual stream of weird packets that don't stop

The last packets are below. No other continual traffic between PC (192.158.1.2) and the tested EVB (192.168.1.1).
![image](https://github.com/user-attachments/assets/f708d825-811f-47f5-9339-e86c0b345fba)

The last packet is from EVB=>PC.
![image](https://github.com/user-attachments/assets/eb24d813-0e73-4c20-a37d-06773797c787)

**Comment by thedjnK** [comment]
Have added more debug, can you try with logger again using https://github.com/thedjnK/AuTerm-Build/actions/runs/11915869906 ? If that doesn't show anything obvious, would you be able to zip the .bin file and upload it here?

**Comment by butok** [comment]
> Have added more debug, can you try with logger again using https://github.com/thedjnK/AuTerm-Build/actions/runs/11915869906 ? If that doesn't show anything obvious, would you be able to zip the .bin file and upload it here?

With more debug. Not able to copy the log as it's not responding, so putted here as the snapshot:
![image](https://github.com/user-attachments/assets/2a074b47-c2eb-4987-a3cd-eceff24d91d9)

Uploaded file:
[mcxn947_zephyr.signed.zip](https://github.com/user-attachments/files/17818033/mcxn947_zephyr.signed.zip)

**Comment by thedjnK** [comment]
I can't replicate this issue, seemingly, that file uploads fine...

**Comment by butok** [comment]
> I can't replicate this issue, seemingly, that file uploads fine...

It was reproduced on both Win10 and Win11. 
The PCs were clean, never installed AuTerm before. 
Just installed: https://aka.ms/vs/17/release/vc_redist.x64.exe and latest Auterm.

We can take as a glitch, and wait if somebody else can reproduce it.

**Comment by thedjnK** [comment]
@butok would you be able to do the memory dump as mentioned above? I've tried with 3 windows 10 devices and can't replicate it so must be something different with OS or the output from the board but without a dump I can't see where it's getting stuck

**Comment by butok** [comment]
> would you be able to do the memory dump as mentioned above?

Dump saved. Try this link: https://drive.google.com/file/d/19vmFFPv8hrRKkeIXwwdB7u0wsIQXESWa/view?usp=sharing

**Comment by thedjnK** [comment]
> > would you be able to do the memory dump as mentioned above?
> 
> Dump saved. Try this link: https://drive.google.com/file/d/19vmFFPv8hrRKkeIXwwdB7u0wsIQXESWa/view?usp=sharing

Seemingly can't access file

**Comment by thedjnK** [comment]
> Please try again: https://drive.google.com/file/d/19vmFFPv8hrRKkeIXwwdB7u0wsIQXESWa/view?usp=sharing

Got it, thanks, will see about how to check a dmp file

**Comment by thedjnK** [comment]
A float value is infinite in a while loop checking the value, that's embarrassing, will fix...

**Comment by butok** [comment]
> Fixed in v0.34c, thanks for reporting!

Confirming - Fixed.
Great ownership.
Thank you.
